apiVersion: v1
data:
  config.yaml: |
    server:
      port: 8080
      host: 0.0.0.0
    database:
      host: postgres.dev.svc.cluster.local
      port: 5432
      ssl: true
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.yaml":"server:\n  port: 8080\n  host: 0.0.0.0\ndatabase:\n  host: postgres.dev.svc.cluster.local\n  port: 5432\n  ssl: true\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"demo"},"name":"app-yaml-config","namespace":"app-dev"}}
  creationTimestamp: "2026-01-10T03:36:17Z"
  labels:
    app: demo
  name: app-yaml-config
  namespace: app-dev
  resourceVersion: "203110"
  uid: 4b5729a2-f3fc-4347-aff4-916ad6f4b576
