apiVersion: v1
data:
  app.json: |
    {
      "server": {
        "port": 8080,
        "host": "0.0.0.0"
      },
      "database": {
        "host": "postgres.dev.svc.cluster.local",
        "port": 5432
      }
    }
  single-line.json: '{"key1":"value1","key2":"value2","nested":{"key3":"value3"}}'
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"app.json":"{\n  \"server\": {\n    \"port\": 8080,\n    \"host\": \"0.0.0.0\"\n  },\n  \"database\": {\n    \"host\": \"postgres.dev.svc.cluster.local\",\n    \"port\": 5432\n  }\n}\n","single-line.json":"{\"key1\":\"value1\",\"key2\":\"value2\",\"nested\":{\"key3\":\"value3\"}}"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"demo"},"name":"app-json-config","namespace":"app-dev"}}
  creationTimestamp: "2026-01-10T03:36:17Z"
  labels:
    app: demo
  name: app-json-config
  namespace: app-dev
  resourceVersion: "203109"
  uid: ba7c9006-0e0a-4765-ae2f-ebafb301e6d6
